name = "ESAAnalytics"
uuid = "ab438be7-21a5-4552-bdb4-455e723b1972"
authors = ["Natapon Wanapinit"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
